### PR TITLE
Integrate librdkafka Metadata API and add partition_key.

### PR DESCRIPTION
**Pull request by Adithya-copart**
This PR introduces a `partition_count` method to the producer that takes a `topic_name` and returns the number of partitions in the topic.

Solves https://github.com/appsignal/rdkafka-ruby/issues/89

- [x] Add the functions in `librdkafka` to access the metadata.
- [x] Expose the partition count of a topic to a producer.
- [x] Support `partition_key` in `Producer#produce`.
- [x] Expose the Metadata in Ruby.
- [x] Add the test cases.

### CODE REVIEW

**Comment by Adithya-copart** [comment]
Test result in a `bundle console` session:

```
def rdkafka_config(config_overrides={})
  config = {
    :"api.version.request" => false,
    :"broker.version.fallback" => "1.0",
    :"bootstrap.servers" => "localhost:9092",
    :"group.id" => "ruby-test-#{Random.new.rand(0..1_000_000)}",
    :"auto.offset.reset" => "earliest",
    :"enable.partition.eof" => false
  }
  if ENV["DEBUG_PRODUCER"]
    config[:debug] = "broker,topic,msg"
  elsif ENV["DEBUG_CONSUMER"]
    config[:debug] = "cgrp,topic,fetch"
  end
  config.merge!(config_overrides)
  Rdkafka::Config.new(config)
end

producer = rdkafka_config.producer

producer.partition_count('rake_test_topic')
# => 3

producer.partition_count('watermarks_test_topic')
# => 3

producer.partition_count('non-existent-topic')
# => nil
```

**Comment by dasch** [comment]
:heart:

**Comment by Adithya-copart** [comment]
The following code results in  3% - 5% of the inputs to end up in the same partition.
I modified the specs to avoid this but we can probably drop this assertion altogether.

```
require 'zlib'

def paritioner(partition_key, partition_count)
  (Zlib.crc32(partition_key) % partition_count)
end

collision_count = 0

10000.times do
  key = ('a'..'z').to_a.shuffle.take(10).join('')
  partition_key = ('a'..'z').to_a.shuffle.take(10).join('')

  result_key =  paritioner(key, 25)
  result_partition_key =  paritioner(partition_key, 25)

  if result_key == result_partition_key
    collision_count += 1
  end
end

collision_count
```

**Comment by dasch** [comment]
👋 any updates on this effort?

**Comment by Adithya-copart** [comment]
Waiting on a review from @thijsc.

**Comment by Adithya-copart** [comment]
@thijsc It does query metadata every time if a `partition_key` is used. There is [metadata cache](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#caching-strategy) in librdkafka as per the docs.

I'll try to get some numbers on the overhead.

**Comment by thijsc** [comment]
Good to hear there's a cache! I think getting the metadata class is a very good thing regardless for the library.

There is also `rd_kafka_topic_conf_set_partitioner_cb` that could be used. I wonder if that approach has a similar overhead, or if it also uses the metadata in a similar way under the hood.

**Comment by thijsc** [comment]
By the way: I've upgraded master to librdkafka 1.4.0, could you rebase?

**Comment by Adithya-copart** [comment]
Will rebase. I think `rd_kafka_topic_conf_set_partitioner_cb` is intended to override the default partitioner in `librdkafka` when `key` is part of the message. The callback provides the  `msg_opaque`, `key` and `partition count` for partition calculation by the client.

In our case, this will not fit our need as `key` is optional and the callback is ignorant of `partition_key`. The callback may not be triggered when a key is absent.

**Comment by Adithya-copart** [comment]
```
$ rvm 2.7.1 do ruby partitioner_results.rb 
Rehearsal ------------------------------------------------------------------
Key                              0.106493   0.003359   0.109852 (  0.107801)
Partition Key                    0.101486   0.002621   0.104107 (  0.102273)
Key + Partition Key              0.114356   0.001739   0.116095 (  0.113317)
None                             0.096901   0.002957   0.099858 (  0.098222)
--------------------------------------------------------- total: 0.429912sec

                                     user     system      total        real
Key                              0.102877   0.001480   0.104357 (  0.102348)
Partition Key                    0.093951   0.002878   0.096829 (  0.094977)
Key + Partition Key              0.094249   0.002103   0.096352 (  0.094394)
None                             0.116031   0.002011   0.118042 (  0.115432)
```

I don't see significant overhead using [this script](https://gist.github.com/Adithya-copart/2dde9b2dc92ead05828ad4edd6b14819).

**Comment by thijsc** [comment]
Sounds good, merging!

**Comment by dasch** [comment]
Awesome!

**Comment by dasch** [comment]
Once this is released I can update Racecar to use it!

**Comment by thijsc** [comment]
I just released `0.8.0.beta.1' with this feature included.

**Comment by thijsc** [comment]
Good to know. Which ones do you think are relevant, or all of them? Let me know if you need help reproducing it in a spec here.

**Pull request merged**
