### PR TITLE
Keep delivery handle from gc

### PR DESCRIPTION
**Pull request by thijsc**

### CODE REVIEW

**Comment by thijsc** [comment]
Continuation of #16

**Comment by thijsc** [comment]
@nurse Looks like this approach does not work in the current incarnation. Multiple calls to `to_ptr` create different pointers, so we cannot reliably use their address as the key in the registry. The registry approach is fine in principle, but we need to find a way to keep the key consistent.

**Comment by thijsc** [comment]
So my diagnosis was slightly wrong. `to_ptr` does return a pointer to the same address. It turns out that the addres needed to be used in the lookup. Fixed this bug and added tests for all this. If the build is green now this should be good to merge.

**Comment by nurse** [comment]
Ah, `message[:_private]` is pointer, not address. Thank you for fix.
CI is failed but it seems just because of travis's temporary failure.

**Comment by thijsc** [comment]
There was a misconfiguration in the CodeClimate config and now the builds don't seem to be exiting properly. Trying some fixes.

**Comment by thijsc** [comment]
Merging, will do a gem release later today.

**Comment by kzk** [comment]
Thank you from Treasure Data team! (CC/ @frsyuki and @nurse)

**Comment by thijsc** [comment]
You're welcome!

**Pull request merged**
