### PR TITLE
allow to use rake 13.x

### PR DESCRIPTION
**Pull request by nijikon**
Closes https://github.com/appsignal/rdkafka-ruby/issues/91

### CODE REVIEW

**Comment by mensfeld** [comment]
Higly appreciated

**Comment by nijikon** [comment]
@thijsc this seems like a random CI error, @mensfeld told me that this happens often. Any idea what is the issue here? I can have a look and fix it if you will explain what might be happening here.

**Comment by thijsc** [comment]
I've been trying to get the Travis build stable for a while now, haven't been successfull so far. If you have any ideas they are very welcome!

**Comment by thijsc** [comment]
Going to merge this, should be fine regardless of the build.

**Pull request merged**
