### PR TITLE
Update to librdkafka v1.5.0

### PR DESCRIPTION
**Pull request by geoff2k**
### The update

The most recent version of librdkafka v1.5.0 was released on [July 20th](https://github.com/edenhill/librdkafka/releases/tag/v1.5.0).  Both it and its two previous version ([v1.4.2](https://github.com/edenhill/librdkafka/releases/tag/v1.4.2) and [v1.4.4](https://github.com/edenhill/librdkafka/releases/tag/v1.4.4)) have multiple fixes we should incorporate.

To verify the SHA256 run the following:

```
$ curl -s https://codeload.github.com/edenhill/librdkafka/tar.gz/v1.5.0 | openssl dgst -sha256
f7fee59fdbf1286ec23ef0b35b2dfb41031c8727c90ced6435b8cf576f23a656
```

### The one regression

There was a single regression in a test in metadata_spec.rb that attempts to get metadata for a non-existent topic.

In 1.5.0, many updates were made related to the handling of unknown topics [note 1](https://github.com/edenhill/librdkafka/compare/v1.4.4...v1.5.0?w=1#diff-d66fa525591da8385b21fcab72e24f28R1461), [note 2 - "Upgrade Considerations"](https://github.com/edenhill/librdkafka/releases/tag/v1.5.0), so the exception raised in this case used to be `RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE`, but is now the more correct `RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART`.

### The bonus content

I added a few reminders to the `ext/README.md` to help future updaters.

### CODE REVIEW

**Comment by thijsc** [comment]
Looking good, I verified the hash. There was a random spec fail, just restarted the build.

**Comment by geoff2k** [comment]
@thijsc I think all builds are good -- these two passed all tests but "failed" due to the usual segfault problem 😢 

https://travis-ci.org/github/appsignal/rdkafka-ruby/jobs/726285456
https://travis-ci.org/github/appsignal/rdkafka-ruby/jobs/726285458

**Comment by thijsc** [comment]
I see this error happen in a few builds:

```
  1) Rdkafka::Admin#delete_topic deletes a topic that was newly created
1012     Failure/Error:
1013       raise RdkafkaError.new(
1014           self[:response],
1015           broker_message: DeleteTopicReport.new(self[:error_string], self[:result_name]).error_string
1016       )
1017     
1018     Rdkafka::RdkafkaError:
1019       Broker: Unknown topic or partition (unknown_topic_or_part)
1020     # ./lib/rdkafka/admin/delete_topic_handle.rb:20:in `raise_error'
1021     # ./lib/rdkafka/abstract_handle.rb:56:in `block in wait'
1022     # ./lib/rdkafka/abstract_handle.rb:49:in `loop'
1023     # ./lib/rdkafka/abstract_handle.rb:49:in `wait'
1024     # ./spec/rdkafka/admin_spec.rb:174:in `block (3 levels) in <top (required)>'
```

The zstd one is being discussed in #132

**Comment by thijsc** [comment]
I've managed to switch to our regular CI provider, so hopefully we will see less build errors. Closing this one in favor of #142.

**Pull request closed without merging**
