### PR TITLE
Update to librdkafka 1.5.3

### PR DESCRIPTION
**Pull request by geoff2k**
_This supercedes #142._

### The update

1.5.3, the most recent version of librdkafka v1.5.x was released on [December 9th](https://github.com/edenhill/librdkafka/releases/tag/v1.5.3).  It and its previous versions have multiple fixes we should incorporate.

To verify the SHA256 run the following:

```
$ curl -s https://codeload.github.com/edenhill/librdkafka/tar.gz/v1.5.3 | openssl dgst -sha256
2105ca01fef5beca10c9f010bc50342b15d5ce6b73b2489b012e6d09a008b7bf
```

### The one regression

There was a single regression in a test in metadata_spec.rb that attempts to get metadata for a non-existent topic.

In 1.5.0, many updates were made related to the handling of unknown topics [note 1](https://github.com/edenhill/librdkafka/compare/v1.4.4...v1.5.0?w=1#diff-d66fa525591da8385b21fcab72e24f28R1461), [note 2 - "Upgrade Considerations"](https://github.com/edenhill/librdkafka/releases/tag/v1.5.0), so the exception raised in this case used to be `RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE`, but is now the more correct `RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART`.

### The bonus content

I added a few reminders to the `ext/README.md` to help future updaters.#146

### CODE REVIEW

**Comment by thijsc** [comment]
Could you force push this branch? I changed the settings on Semaphore so it'll run the specs for forked pull requests too.

**Comment by geoff2k** [comment]
@thijsc done!

**Comment by thijsc** [comment]
It's working on all MRIs, but something's broken on jRuby.

**Comment by geoff2k** [comment]
@thijsc So far, I have not been able to reproduce this locally with jruby-9.2.13.0, but I have libzstd installed.  I'll try removing it from the equation to see if it changes anything...

**Comment by geoff2k** [comment]
I just noticed that the jruby failiures between this build and #148 (adding Ruby 3.0 to the builds) are the same...

```
rspec ./spec/rdkafka/producer_spec.rb:312 # Rdkafka::Producer should produce message that aren't waited for and not crash​05:31
rspec ./spec/rdkafka/producer_spec.rb:386 # Rdkafka::Producer should raise an error when producing fails​05:31
rspec ./spec/rdkafka/producer_spec.rb:397 # Rdkafka::Producer should raise a timeout error when waiting too long​05:31
rspec ./spec/rdkafka/producer_spec.rb:15 # Rdkafka::Producer delivery callback should set the callback​05:31
rspec ./spec/rdkafka/producer_spec.rb:24 # Rdkafka::Producer delivery callback should not accept a callback that's not a proc​05:31
rspec ./spec/rdkafka/producer_spec.rb:30 # Rdkafka::Producer delivery callback should call the callback when a message is delivered​05:31
rspec ./spec/rdkafka/producer_spec.rb:178 # Rdkafka::Producer timestamp should raise a type error if not nil, integer or time​05:31
rspec ./spec/rdkafka/producer_spec.rb:189 # Rdkafka::Producer timestamp should produce a message with an integer timestamp​05:31
rspec ./spec/rdkafka/producer_spec.rb:210 # Rdkafka::Producer timestamp should produce a message with a time timestamp​05:31
rspec ./spec/rdkafka/producer_spec.rb[1:16:1] # Rdkafka::Producer methods that should not be called after a producer has been closed raises an exception if produce is called​05:31
rspec ./spec/rdkafka/producer_spec.rb[1:16:2] # Rdkafka::Producer methods that should not be called after a producer has been closed raises an exception if partition_count is called
```
... and they all involve the DeliveryHandle registry not being clear when we start a spec.   I'll add some test code to troubleshoot around why the registry is not clear.

**Comment by thijsc** [comment]
Closing in favor of #152

**Pull request closed without merging**
