### PR TITLE
upgrade librdkafka to v2.0.2

### PR DESCRIPTION
**Pull request by leonmaia**
Upgrades librdkafka to version 2.0.2, this version contains several improvements and bugfixes. For a full list of the changes please refer to https://github.com/confluentinc/librdkafka/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by mensfeld** [comment]
0.13 is in beta, so I would suggest still target 0.13 with it or even 0.12.1 until we solve problems with stability in 0.13. That way this could be backported as 0.12.1 and then updated in the main. WDYT?

**Comment by leonmaia** [comment]
good call @mensfeld I'm bumping the beta count on 0.13.

**Comment by mensfeld** [comment]
@leonmaia @thijsc I think it should go to `0.12.1`. `0.13.0` will change how the locks operate and I would not release it together with this. I did bump it to my fork and I executed all the integrations: works and is stable. I am crafting 0.12.1 for myself: https://github.com/karafka/karafka-rdkafka/tree/v0.12.1

**Comment by mensfeld** [comment]
I released it to karafka - no issues there. Works stable after bump with 0.12.

**Comment by mensfeld** [comment]
@thijsc ping ;)

**Comment by mensfeld** [comment]
@leonmaia can you rebase please? :pray:

**Comment by mensfeld** [comment]
@thijsc lets release it with the upcoming one ok? It solves some of the rebalance problems and aligns with karafka-rdkafka releases. It is also heavily tested by me & karafka users and there are no breaking changes.

**Comment by mensfeld** [comment]
@leonmaia sorry it took so long. I had to clean up memory leaks and fix few other things to make sure it operates as expected.

**Comment by thijsc** [comment]
>  lets release it with the upcoming one ok? I

👍

**Pull request merged**
