### PR TITLE
Allow customizing the wait time for delivery report availability recheck and use monotonic clock for time estimates

### PR DESCRIPTION
**Pull request by mensfeld**
This PR allows customizing the delivery report recheck wait timeout.

I did normalize the variables namings but they aren't kwargs, so no API incompatibilities introduced.

I'm building new version of WaterDrop producer and this setting is needed in order to provide a more robust and efficient sync producer. What this sleep does (when not configurable) from a sync perspective, is creating a hidden "throttling" layer that elevates the single message sync delivery up to min 100 ms (when not scheduled extremely fast not to hit the first sleep).

Here's an example (the number if brackets is the sleep + the operation time):

```
I, [2019-08-13T16:08:05.865263 #6102]  INFO -- : Sync producing of a message to 'e2r12r1' topic
D, [2019-08-13T16:08:05.865303 #6102] DEBUG -- : [101]
I, [2019-08-13T16:08:05.965778 #6102]  INFO -- : Sync producing of a message to 'e2r12r1' topic
D, [2019-08-13T16:08:05.965819 #6102] DEBUG -- : [100]
```

on top of that I also fixed two other things:

- Allow using non-integer max timeout
- Use monotonic clock that is resistant to a system clock changes.

### CODE REVIEW

**Comment by mensfeld** [comment]
CI failed on one version - does not look related but I don't have a way to restart.

**Comment by tombruijn** [comment]
@mensfeld thanks for the PRs and issues!
@thijsc is on holiday right now and will look at them when he gets back in 2 weeks time.

Ping me if you need a future build restarted.

**Comment by mensfeld** [comment]
@tombruijn thanks. I figured out, you can trigger a rebuild by force pushing an empty commit ;)
The only downside is, that you will have to squash merge not to have them in the master.

**Comment by thijsc** [comment]
Looks good. I think it'd rather use keyword arguments here too. Only reason I didn't is that I didn't expect more arguments. Also wondering, could the wait timeout be configuration? Do you really need to be able to tweak it every time you call `wait`?

**Comment by mensfeld** [comment]
> Looks good. I think it'd rather use keyword arguments here too.

You want me to replace it with `kwargs`?

> Also wondering, could the wait timeout be configuration? Do you really need to be able to tweak it every time you call wait?

I do have a case for that. I'm almost done with new waterdrop release. Waterdrop is used by streamy (https://github.com/cookpad/streamy) (cc @lewispb), they have different policies in reference to the importance of a message (and other factors) and I can imagine the timeouts being used the same way with a single producer instance.

We could move the defaults to the config, however as it is now, the handler has no notion of the producer config, thus it would require way more work to achieve the same thing.

I did follow the current API ;)

**Comment by thijsc** [comment]
Makes sense. Could you change it to use keyword args? We’ll make that the default in this gem for any method with more than one arg. I think it’s good to merge then.

**Comment by mensfeld** [comment]
@thijsc the errors seem to be more travis related than the code.

**Comment by mensfeld** [comment]
@thijsc could we get this merged? It's blocking my further work :(

**Comment by thijsc** [comment]
I think it's good to merge, but Travis is having a hard time pulling of a green build :-(. Just restarted again.

**Comment by mensfeld** [comment]
@thijsc it's semi-green with random failures in random places :D tbh Travis does not behave well recently...

**Comment by thijsc** [comment]
Just restarted only the two that failed now. This is annoying indeed.

**Comment by mensfeld** [comment]
@thijsc just one more: https://travis-ci.org/appsignal/rdkafka-ruby/jobs/573702454 :D not the most reliable setup hehehe

**Comment by thijsc** [comment]
The 2.3 build keeps failing, just restarted it now.

I need to come up with a fix for this CI issue, will probably merge without a green build in a bit.

**Comment by thijsc** [comment]
Ah I see that Ruby 2.3 is EOL already, will remove it from the build.

**Comment by thijsc** [comment]
Removed 2.3 support: ec984859d310e5c446fb3ce3f4c64e1c595e82aa. Could you rebase on `master`?

**Comment by mensfeld** [comment]
argh.... restarts, restarts :(

**Comment by mensfeld** [comment]
@thijsc https://travis-ci.org/appsignal/rdkafka-ruby/jobs/582576360 ;) click plz. I really need this one for my further work.

**Comment by thijsc** [comment]
I'm just going to merge and work on a more reliable CI setup separately.

**Comment by mensfeld** [comment]
Hehehe. Thanks! Looking forward to a release now ;)

**Comment by thijsc** [comment]
Just released 0.7.0 which includes this change.

**Pull request merged**
