### PR TITLE
fix travis builds

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mensfeld** [comment]
Irony: now all fail :D which is good - at least a bit of predictability :dancer:

**Comment by rgo** [comment]
Locally, if I run consumer_spec.rb it consistently fails (Assertion failed error) in #seek subscription:

```
Rdkafka::Consumer
  #subscripe, #unsubscribe and #subscription
    should subscribe, unsubscribe and return the subscription
    should raise an error when subscribing fails
    should raise an error when unsubscribing fails
    should raise an error when fetching the subscription fails
  #pause and #resume
    should raise when not TopicPartitionList
    should raise an error when pausing fails
    should raise an error when resume fails
    subscription
      should pause and then resume
  #seek
    should raise an error when seeking fails
    subscription
Assertion failed: (r == 0), function rwlock_wrlock, file tinycthread_extra.c, line 138.

[Process exited 134]
```

Running #seek context isolated works.

**Comment by rgo** [comment]
> Irony: now all fail :D which is good - at least a bit of predictability 💃

It seems to be failing because `dockerize` is not installed or something like that:

```
$ dockerize -wait tcp://localhost:2181 -timeout 1m
dockerize: command not found
```
https://travis-ci.org/appsignal/rdkafka-ruby/jobs/606363122#L421

**Comment by nijikon** [comment]
@mensfeld @rgo this is a draft, be patient 😸

**Comment by nijikon** [comment]
@thijsc could you give me some more privileges so I can cancel builds on travis? Right now I can't.

**Comment by thijsc** [comment]
I'm also working on this in #98

**Comment by thijsc** [comment]
Did you get a green build locally by the way?

**Comment by thijsc** [comment]
Thanks for your work on this! The build was fixed in #108 in the end.

**Pull request closed without merging**
