### PR TITLE
Add Consumer#consume_with_queue

### PR DESCRIPTION
**Pull request by Paxa**
* Add Consumer#consume_with_queue
* Add Consumer#fetch_partitions_count
* Add Consumer#reset_offsets
* Add benchmarks
* Change require to require_relative
* Add Rdkafka.print_ffi_obj for debugging

`consume_with_queue` is about 20-30% faster in benchmarks and hopefully be more efficient with real loads. Will test with real app later and show numbers

---

Example of output by `Rdkafka.print_ffi_obj`
```
Rdkafka::Bindings::KafkaMetadata
* broker_cnt: 1
* brokers: #<FFI::Pointer address=0x00007f7fa958c478>
* topic_cnt: 1
* topics: #<FFI::Pointer address=0x00007f7fa958c4a0>
* orig_broker_id: 1001
* orig_broker_name: "localhost:9092/1001"

Rdkafka::Bindings::KafkaMetadataTopic
* topic: "rake_test_topic"
* partition_cnt: 3
* partitions: #<FFI::Pointer address=0x00007f7fa958c4d0>
* err: 0
```

---

I could not implement reading in batches, it gives me array of messages but I'm not sure how to handle it correctly with ffi

### CODE REVIEW

**Comment by Paxa** [comment]
With real apps I see improvements by 15-25%, less significant than I expected

**Comment by thijsc** [comment]
Hi Paxa, thanks for your work on this!

I'm always open to good arguments that might convince me otherwise, but supporting the legacy consumer is not something I want to add. I talked about this a bit in the readme:

> This gem only provides a high-level Kafka consumer. If you are running an older version of Kafka and/or need the legacy simple consumer we suggest using the Hermann gem.

Our purpose with this gem was providing a production-ready way for people to use all the modern Kafka features. It is explicitly not a goal to support the old way of doing things. If you want the old way I think Hermann is a perfectly fine alternative to this gem.

So anything that's marked as legacy in rdkafka's doc is not going to be supported here. I think that's the best course to keep this project focussed and maintainable. So I'm afraid I'm not going to merge this change even if it were completely finished. Do you have any great arguments that you think need to be made?

**Comment by Paxa** [comment]
Just though it will have better performance if process in batches, but I could not use batch api.
I started to look into it because my consumer works slower then I expected, I see pauses between processing several messages.

Other things in this PR are just useful to run examples and benchmarks.

About changing `require` to `require_relative` - rake tasks doesn't work with usual require

**Comment by Paxa** [comment]
Btw how do we know which functions are deprecated?

**Comment by thijsc** [comment]
We do have an issue open to poll in batches btw: #57.

I mean "legacy" instead of deprecated. Most of rdkafka is not, but the simple consumer is. Did you try just assigning and not subscribing with the high level consumer btw? Maybe that's as fast as the simple consumer since it does the same approach.

**Comment by Paxa** [comment]
What non-legacy API can we use to implement poll in batches?

**Comment by thijsc** [comment]
> What non-legacy API can we use to implement poll in batches?

Good question, will answer over in #57

**Pull request closed without merging**
