### PR TITLE
Use non-global statistics and error callbacks

### PR DESCRIPTION
**Pull request by mensfeld**
Hey, giving a shot to fix this: https://github.com/appsignal/rdkafka-ruby/issues/82

This PR introduces a per config interface to provide callback objects for statistics and errors. It allows for a better separation of responsibilities when several producers or consumers are used.

It also includes specs to make sure, that when we have more than one producer / consumer, their callbacks do not interact with each other.

### CODE REVIEW

**Comment by mensfeld** [comment]
Failing sub-specs seem unrelated.

**Comment by mensfeld** [comment]
@thijsc ping pretty please :pray:

**Comment by thijsc** [comment]
I think this should work well. Did you test what happens if you mix create consumers/producers from both single and multiple configs?

**Comment by mensfeld** [comment]
> I think this should work well. Did you test what happens if you mix create consumers/producers from both single and multiple configs?

I did. I just wanted to get a confirmation, that the direction I'm heading is ok (closure around FFI). I will add appropriate specs to handle the cases you've asked.

**Comment by mensfeld** [comment]
Please don't merge yet despite :green_heart: I'm going to rework the log callback and add specs to make sure that callbacks do not interact with each other.

**Comment by mensfeld** [comment]
Closing this one unless anyone else needs it (then I can continue working on it). I was able to bypass this by getting the instance name from librdkafka and using it to filter out the callbacks that are published, hence this change won't be needed by me anymore.

**Comment by Ruto8** [comment]
@mensfeld, thoughts about re-opening this? We want to use the stats callback, but the global nature of it stops us. I saw the workaround in Waterdrop, but I'm reluctant to implement it myself.

I was thinking about contributing, but your PR is everything we need.

**Comment by mensfeld** [comment]
@Ruto8 not at the moment. There are couple of things related to global state and defaults that I want to tackle altogether in the near future. Just need to finalize some other work. I would suggest for now to go with waterdrop solution and we can coop on a proper PR in the near future. waterdrop solution is 100% reliable and stable. Any change to callbacks logic here needs to be extremely well tested (which I do) and I must be super cautious about it.

**Pull request closed without merging**
