### PR TITLE
Add error to delivery report

### PR DESCRIPTION
**Pull request by AlexStanovsky**
Adding error to verify / log that the produce was successful

### CODE REVIEW

**Comment by thijsc** [comment]
Looks good, having a hard time getting Travis to a green build atm.

**Comment by mensfeld** [comment]
@thijsc can we merge this one? There's one more issue that I will report that might need this.

**Comment by thijsc** [comment]
Just restarted the build.

**Comment by thijsc** [comment]
I'm working on getting a green build again, that's been very shaky.

Looking at this again I'm wondering if we should raise an error in `DeliveryHandle#wait` instead. That' d be more in line with expectations probably. What do you think?

**Comment by thijsc** [comment]
Sorry, got confused for a second. We already do, this change just adds it to possible callbacks.

**Comment by AlexStanovsky** [comment]
How can I help with making the build pass ?

**Comment by mensfeld** [comment]
@AlexStanovsky @nijikon is fixing that.

**Comment by thijsc** [comment]
This is blocked on getting the build green in #98, will merge as soon as we have a green build again.

**Comment by AlexStanovsky** [comment]
Can we merge this ?

**Comment by yosiat** [comment]
@thijsc hi! I am alex's co-worker, I pushed a rebase and now CI passes 🚀 
Can we merge this PR (and maybe release a version?) ?

**Comment by AlexStanovsky** [comment]
Hi @AlexStanovsky we will appreciate your help

**Comment by yosiat** [comment]
@thijsc Thanks for merging this!

**Comment by yosiat** [comment]
@thijsc when you plan to release a version? we currently rely on our branch and want to use the official version from RubyGems.

**Pull request merged**
